FROM  carlasim/carla:0.9.11
USER root
RUN apt update && apt install -y curl
USER carla
RUN curl -L http://cloudiepcc.unex.es/index.php/s/djK6e6FbYHe3dqE/download --output /home/carla/Import/map.tar.gz
RUN cd /home/carla/ && sh ImportAssets.sh
RUN rm /home/carla/Import/map.tar.gz
RUN curl -L  http://cloudiepcc.unex.es/index.php/s/f5HzNsLFQNSQ5pa/download --output  /home/carla/CarlaMelexCar.tar.gz
RUN tar -xvzf CarlaMelexCar.tar.gz
RUN rm /home/carla/CarlaMelexCar.tar.gz
