//******************************************************************
// 
//  Generated by RoboCompDSL
//  
//  File name: AdminBridge.ice
//  Source: AdminBridge.idsl
//
//******************************************************************
#ifndef ROBOCOMPADMINBRIDGE_ICE
#define ROBOCOMPADMINBRIDGE_ICE
module RoboCompAdminBridge
{
	interface AdminBridge
	{
		bool activateSensor (int IDSensor);
		bool stopSensor (int IDSensor);
	};
};

#endif
